### ISSUE TITLE
issue with comments

### ISSUE THREAD

**Issue by ctf0** [victorhqc/nyan-indent#4]
this is mostly related to comments in php
```php
    /**
     * Accessors.
     *
     * @param mixed $value
     */
```

![demo](https://user-images.githubusercontent.com/7388088/35382324-8931b104-01c7-11e8-8ef5-fc24828953d0.png)

**Comment by victorhqc** [comment]
I'm sorry, I didn't notice this issue before. Thanks for reporting, I'll keep you posted ;)
